### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by iippa73** [taroquu/CordovaNavbarPlugin#1]
Hi and thanks for useful plugin!

I'm just having trouble with compiling it. Does not seem to find 'UI' namespace of WPCordovaClassLib.Cordova. Something missing in my setup or should I somehow prepare cordova environment with something extra? If yes, perhaps you could add instructions what I should do?

I have:
- windows 8.1 pro 64bit
- visual studio for windows 2013 express update 4
- cordova 4.3.0 (tried also with 5.0.0)

After adding your plugin and trying to compile it for wp8 I get:
$ cordova build wp8
Running command: c:\Users\kotsa\ohjelmointi\repositories\hello\platforms\wp8\cordova\build.bat
Building project: c:/Users/kotsa/ohjelmointi/repositories/hello/platforms/wp8/HelloWorld.sln
        Configuration : debug
        Platform      : any cpu
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Plugins\cordova.plugins.navbar\NavBar.cs(12,33): error CS0234: The type or namespace name 'UI' does not exist in the na
mespace 'WPCordovaClassLib.Cordova' (are you missing an assembly reference?) [c:\Users\kotsa\ohjelmointi\repositories\h
ello\platforms\wp8\HelloWorld.csproj]
ERROR: Error code 1 for command: C:\Program Files (x86)\MSBuild\12.0\bin\msbuild with args: c:/Users/kotsa/ohjelmointi/r
epositories/hello/platforms/wp8/HelloWorld.sln,/clp:NoSummary;NoItemAndPropertyList;Verbosity=minimal,/nologo,/p:Configu
ration=debug,/p:Platform=any cpu
ERROR building one of the platforms: Error: c:\Users\kotsa\ohjelmointi\repositories\hello\platforms\wp8\cordova\build.ba
t: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: c:\Users\kotsa\ohjelmointi\repositories\hello\platforms\wp8\cordova\build.bat: Command failed with exit code 2
    at ChildProcess.whenDone (c:\Users\kotsa\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordo
va\superspawn.js:131:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)

If I remove plugin, I can build and deploy to my windows phone without problems.

**Comment by taroquu** [comment]
It was written for cordova 4.3.
What version of the windows phone sdk are you using?

**Comment by iippa73** [comment]
visual studio for windows 2013 express update 4

So, you don't have anything extra installed on your environment? Something that would bring 'UI' namespace to WPCordovaClassLib.Cordova?

**Comment by taroquu** [comment]
I see what you mean now. That namespace was actually coming from the cordova notifications plugin and wasn't even used. I've just pushed an update which removes all the unused imports.

**Comment by iippa73** [comment]
Cool, got it working! Thanks!
